{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">首页</h5>
        <div class="clear"></div>
    </div>
    <div class="start-main">
        <h3>网站概要</h3>
        <p>目前有 <i>{$section_count}</i> 个栏目,  <i>{$content_count}</i> 篇资讯,  <i>{$user_count}</i> 个用户.</p>
        <p>点击下面的链接快速开始:</p>
        <ul class="start-link">
            <li><a href="content.php?act=add" target="_blank">添加资讯</a></li>
            <li><a href="section.php?act=add" target="_blank">添加栏目</a></li>
            <li><a href="admin.php" target="_blank">用户管理</a></li>
            <li><a href="sysconf.php" target="_blank">系统设置</a></li>
        </ul>
    </div>
</div>
<!-- END content -->

{include file="library/footer.lbi"}
</body>
</html>
