<form name="admin-login-form" method="post" >
    帐号：<input type="text" name="account" />
    <span style="color: #ff0000">{if $error.account}{$error.account}{/if}</span>
    密码：<input type="password" name="password" />
    <span style="color: #ff0000">{if $error.password}{$error.password}{/if}</span>
    <input type="submit" name="login" value="登陆" />
    <input type="hidden" name="opera" value="login" />
</form>