<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{$page_title}-{$config.site_name}</title>
    <meta name="keywords" content="{$section.keywords}">
    <meta name="description" content="{$section.description}">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="{$template_dir}js/jquery.js"></script>
    <script type="text/javascript" src="{$template_dir}js/banner.js"></script>

</head>
<body>
{include file="header.phtml"}

<div class="banner0">
    <img src="{$template_dir}images/banner01.gif" alt="">
</div>

<div class="clear"></div>

<div class="main_n">
<div class="nleft">
    {include file="slider.phtml"}    
</div>

    <div class="nright">
        <div class="mbx">
            你现在的位置：<a href="index.php">主页</a> > <a href="{$script}">{$page_title}</a>
        </div>
        <div class="list">
            {if $article_list}
            <ul>
                {foreach from=$article_list name=article_list item=article}
                <li><a href="article.php?id={$article.id}" >{$article.title}</a></li>
                {/foreach}
            </ul>
            {else}
            <h2>当前栏目下没有发布任何文章</h2>
            {/if}
        </div>
        {if $total_page gt 1}
        <div class="pagelist">
            <ul>
                <li><a href="{$script}">首页</a></li>
                {for $i=1 to $total_page}
                {if $i eq $page}
                <li class="thisclass">{$i}</li>
                {else}
                <li><a href="{$script}&page={$i}">{$i}</a></li>
                {/if}
                {/for}
                {assign var=next_page value=($page+1)}
                {if  $next_page <= $total_page}
                <li><a href="{$script}&page={$page+1}">下一页</a></li>
                {/if}
                <li><a href="{$script}&page={$total_page}">末页</a></li>
                <li><select name='sldd' style='width:36px' onchange='location.href=this.options[this.selectedIndex].value;'>
                    {for $i=1 to $total_page}
                    <option value="{$script}&page={$i}" {if $i eq $page}selected="selected"{/if}>{$i}</option>
                    {/for}
                </select></li>
            </ul>
        </div>
        {/if}
    </div>
</div>

<div class="clear"></div>

{include file="footer.phtml"}
</body>

</html>
