<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{$page_title}-{$config.site_name}</title>
    <meta name="keywords" content="{$article.keywords}">
    <meta name="description" content="{$article.description}">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="{$template_dir}js/jquery.js"></script>
    <script type="text/javascript" src="{$template_dir}js/banner.js"></script>

</head>
<body>
{include file="header.phtml"}

<div class="banner0">
    <img src="{$template_dir}images/banner01.gif" alt="">
</div>

<div class="clear"></div>

<!--  main  -->
<div class="main_n">
<div class="nleft">
    {include file="slider.phtml"}
</div>

    <div class="nright">
        <div class="mbx">
            你现在的位置：<a href="index.php">主页</a> > <a href="article_list.php?id={$section.id}">{$section.section_name}</a>
        </div>
        <div class="artcontent">
            <h1>{$article.title}</h1>
            <div class="laiyuan">作者：{$article.author} 发布日期:{$article.add_time}</div>
            <div class="body">
            {$article.content}
            </div>
        </div>
    </div>
</div>

<div class="clear"></div>

{include file="footer.phtml"}
</body>

</html>
