<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{$config.site_name}</title>
    <meta name="keywords" content="{$config.keywords}">
    <meta name="description" content="{$config.description}">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="{$template_dir}js/jquery.js"></script>
    <script type="text/javascript" src="{$template_dir}js/banner.js"></script>

</head>

<body>
{include file="header.phtml"}
<div class="banner">
    <div class="banners">
        <div class="show">
            <ul>
                <li style="display: list-item;"><a href="#"><img src="{$template_dir}images/banner1.gif" alt=""></a></li>
                <li style="display: none;"><a href="#"><img src="{$template_dir}images/banner2.gif" alt=""></a></li>
                <li style="display: none;"><a href="#"><img src="{$template_dir}images/banner3.gif" alt=""></a></li>
            </ul>
        </div>
        <div class="hot">
            <div class="wrapper">
                <span>最新动态：</span><a href="#"><font color="#FF0000">2014年9月17日福田区财政局领导来我司考察工作</font></a>
                <div class="focus">
                    <a href="javascript:void(0);" class="on"></a>
                    <a href="javascript:void(0);" class=""></a>
                    <a href="javascript:void(0);" class=""></a>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="clear"></div>

<!--  main  -->
<div class="main_m">
<!-- Editable Begin -->
<h2 class="flow-title">业务办理流程</h2>
<div class="flow">
    <ol class="flow-step-1">
        <li>1. 公司名称预查</li>
        <li>2. 公司名称预先核准</li>
        <li>3. 客户提供注册地址（或我司提供商务秘书地址）</li>
    </ol>
    <ol class="flow-step-2">
        <li>4. 确认公司经营范围及经营期限等相关设立信息</li>
        <li>5. 认缴制公司注册，股东及法人对注册文件进行电子签名</li>
        <li>6. 公司设立提交</li>
    </ol>
    <ol class="flow-step-3">
        <li>7. 设立申请经审批通过，领取四证 (营业执照、税务登记证、组 织机构代码证、刻章许可证、公司数字证书(可选))</li>
        <li>8. 刻章（公章、财务章、法人私章、发票专用章(可选))</li>
    </ol>
</div>
<h2 class="reason-title">选择<span style="color:red">君德财税</span>的4大理由</h2>
<div class="reason">
    <dl class="reason-dl reason-dl1">
        <dt>服务专业</dt>
        <dd>记帐人员专业知识强、经验丰富，且能及时掌握相关政策的变化，为客户提供全面服务。</dd>
    </dl>
    <dl class="reason-dl reason-dl2">
        <dt>安全保密</dt>
        <dd>安全权威的财务机构，为经营者保驾护航。我们坚决维护客户利益，绝不外泄客户公司机密。</dd>
    </dl>
    <dl class="reason-dl reason-dl3">
        <dt>财税指导</dt>
        <dd>资深会计师领衔，专业团队做账，严把质量关，免去您疲于应付工商、税务等部门，尽力规避财务税务风险。</dd>
    </dl>
    <dl class="reason-dl reason-dl4">
        <dt>节省费用</dt>
        <dd>按财务制度要求，一般企业财务人员设三人，出纳一人，会计两人。委托会计公司代理记帐后，企业只需设一名出纳，减少了会计费用支出。</dd>
    </dl>
</div>
<!-- Editable End -->
    <div class="news">
        <div class="szwz">
            <script type="text/javascript">
                function nTabs0(thisObj,Num){
                    if(thisObj.className == "active0")return;
                    var tabObj = thisObj.parentNode.id;
                    var tabList = document.getElementById(tabObj).getElementsByTagName("li");
                    for(i=0; i < tabList.length; i++)
                    {
                        if (i == Num)
                        {
                            thisObj.className = "active0";
                            document.getElementById(tabObj+"_Content"+i).style.display = "block";
                        }else{
                            tabList[i].className = "normal0";
                            document.getElementById(tabObj+"_Content"+i).style.display = "none";
                        }
                    }
                }
            </script>

            <div class="cate_t">
                <ul id="myTab0">
                    <li class="active0" onclick="nTabs0(this,0);">深圳公司注册</li>
                    <li class="normal0" onclick="nTabs0(this,1);">外资公司注册</li>
                    <ul>
                    </ul></ul></div>
            <div class="content" id="myTab0_Content0" style="display: block; ">
                <dl>
                    {foreach from=$article_list.2 name=article2 item=article}
                    <dd><a href="article.php?id={$article.id}" title="{$article.title}">{$article.title}</a></dd>
                    {/foreach}
                </dl>
            </div>
            <div class="content" id="myTab0_Content1" style="display: none; ">
                <dl>
                    {foreach from=$article_list.3 name=article3 item=article}
                    <dd><a href="article.php?id={$article.id}" title="{$article.title}">{$article.title}</a></dd>
                    {/foreach}
                </dl>
            </div>
        </div>

        <div class="qhcj">
            <script type="text/javascript">
                function nTabs(thisObj,Num){
                    if(thisObj.className == "active1")return;
                    var tabObj = thisObj.parentNode.id;
                    var tabList = document.getElementById(tabObj).getElementsByTagName("li");
                    for(i=0; i < tabList.length; i++)
                    {
                        if (i == Num)
                        {
                            thisObj.className = "active1";
                            document.getElementById(tabObj+"_Content"+i).style.display = "block";
                        }else{
                            tabList[i].className = "normal1";
                            document.getElementById(tabObj+"_Content"+i).style.display = "none";
                        }
                    }
                }
            </script>

            <div class="cate_t">
                <ul id="myTab1">
                    <li class="active1" onclick="nTabs(this,0);">前海公司注册</li>
                    <li class="normal1" onclick="nTabs(this,1);">常见问题</li>
                    <ul>
                    </ul></ul></div>
            <div class="content" id="myTab1_Content0" style="display: block; ">
                <dl>
                    {foreach from=$article_list.4 name=article4 item=article}
                    <dd><a href="article.php?id={$article.id}" title="{$article.title}">{$article.title}</a></dd>
                    {/foreach}
                </dl>
            </div>
            <div class="content" id="myTab1_Content1" style="display: none; ">
                <dl>
                    {foreach from=$article_list.6 name=article6 item=article}
                    <dd><a href="article.php?id={$article.id}" title="{$article.title}">{$article.title}</a></dd>
                    {/foreach}
                </dl>
            </div>


        </div>
        <div class="gszc">
            <dl>
                <dt>我要注册？</dt>
                {foreach from=$article_list.8 name=article8 item=article}
                {if $smarty.foreach.article8.iteration%2}
                <dd><a href="article.php?id={$article.id}" target="_blank">{$article.title}</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                {else}
                <a href="article.php?id={$article.id}" target="_blank">{$article.title}</a></dd>
                {/if}
                {/foreach}
            </dl>
        </div>
    </div>
</div>

<div class="clear"></div>
{include file="footer.phtml"}
</body>
</html>
