<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{$config.site_name}</title>
    <meta name="keywords" content="{$config.keywords}">
    <meta name="description" content="{$config.description}">
    <link href="{$template_dir}css/style.css" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="{$template_dir}js/jquery.js"></script>
    <script type="text/javascript" src="{$template_dir}js/banner.js"></script>

</head>

<body>
{include file="header.phtml"}
<div class="banner">
    <div class="banners">
        <div class="show">
            <ul>
                <li style="display: list-item;"><a href="neizi_zc/200.html"><img src="{$template_dir}images/banner1.gif" alt=""></a></li>
                <li style="display: none;"><a href="neizi_zc/200.html"><img src="{$template_dir}images/banner2.gif" alt=""></a></li>
                <li style="display: none;"><a href="jizhang/199.html"><img src="{$template_dir}images/banner3.gif" alt=""></a></li>
            </ul>
        </div>
        <div class="hot">
            <div class="wrapper">
                <span>最新动态：</span><a href="news/218.html"><font color="#FF0000">2014年9月17日福田区财政局领导来我司考察工作</font></a>
                <div class="focus">
                    <a href="javascript:void(0);" class="on"></a>
                    <a href="javascript:void(0);" class=""></a>
                    <a href="javascript:void(0);" class=""></a>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="clear"></div>

<!--  main  -->
<div class="main_m">
    <div class="fuwu">
        <div class="title">精品服务</div>
        <dl>
            <dt><a href="neizi_zc/200.html"><img src="{$template_dir}images/fw1.gif" alt="圆梦一号1元注册深圳公司"></a></dt><a href="neizi_zc/200.html">
        </a><dd class="fw1"><a href="neizi_zc/200.html"></a><a href="neizi_zc/200.html"><font color="#FF0000">1元</font>注册深圳公司</a></dd>
            <dd><a href="neizi_zc/200.html">2014深圳公司注册新政策：注册资金实行认缴制；注册地址放宽，住宅地址也可注册；新版营业执照不显示注册资金及经营范围…</a><a href="waizi_zc/"></a></dd><a href="waizi_zc/">
        </a><dd class="fw2"><a href="waizi_zc/"></a><a href="neizi_zc/200.html"><img src="{$template_dir}images/detail.gif"></a></dd>
        </dl>
        <dl>
            <dt><a href="waizi_zc/"><img src="{$template_dir}images/fw2.gif" alt="圆梦一号外资公司注册"></a></dt><a href="waizi_zc/">
        </a><dd class="fw1"><a href="waizi_zc/"></a><a href="waizi_zc/">深圳外资公司注册</a></dd>
            <dd><a href="waizi_zc/">一站式服务：公司设立前的法律、人力咨询，公司注册，财务外包，税务咨询，以及行政管理、合规管理、重组等合规管理、重组等…</a></dd>
            <dd class="fw2"><a href="waizi_zc/"><img src="{$template_dir}images/detail.gif"></a></dd>
        </dl>
        <dl>
            <dt><a href="qianhai/"><img src="{$template_dir}images/fw3.gif" alt="圆梦一号前海公司注册"></a></dt><a href="qianhai/">
        </a><dd class="fw1"><a href="qianhai/"></a><a href="qianhai/">深圳前海公司注册</a></dd>
            <dd><a href="qianhai/">深圳前海，“特区中的特区”，肩负着推进现代服务业的开放与合作，深化改革、扩大开放的战略试验田使命，在税收、土地等方面有优惠…</a></dd>
            <dd class="fw2"><a href="qianhai/"><img src="{$template_dir}images/detail.gif"></a></dd>
        </dl>
        <dl>
            <dt><a href="jizhang/199.html"><img src="{$template_dir}images/fw4.gif" alt="圆梦一号财务代理"></a></dt><a href="jizhang/199.html">
        </a><dd class="fw1"><a href="jizhang/199.html"></a><a href="jizhang/199.html">代理记账报税</a></dd>
            <dd><a href="jizhang/199.html">《会计法》第36条明确规定：“不具备设置条件的应当委托经批准设立从事会计代理记账业务的中介机构代理记账机构代理记账。”...</a></dd>
            <dd class="fw2"><a href="jizhang/199.html"><img src="{$template_dir}images/detail.gif"></a></dd>
        </dl>
    </div>

    <div class="tese1">
        <div class="catet">
            <dl>
                <dt>专业快速 <span>全程免费</span>代办</dt>
                <dd class="tinfo">您:不了解注册公司流程及费用？不清楚所需资料有哪些？不知道去哪办理？……怕麻烦，没时间？</dd>
                <dd>
                    <ul>
                        <li>我们为您提供<span>手续全包，费用全免</span>；</li>
                        <li>我们拥有<span>专业团队、丰富经验、庞大资源</span>；</li>
                        <li>我们竭诚为您<span>7天办结、让您尽早营业赚大钱!</span></li>
                    </ul>
                </dd>
            </dl>
        </div>
        <div class="cateb">
            <dl>
                <dt>创业开支大？<span>创业基金</span>帮扶您</dt>
                <dd class="tinfo">注册深圳公司费用（原价）：<span>1600元</span>；</dd>
                <dd class="tinfo">但，选择我们代理注册，您仅需<span>1元</span>；</dd>
                <dd class="tinfo">您将享受：<span>免收注册代理费、获赠600元创业扶持基金</span>（即垫付工本费）；</dd>
                <dd>
                    <ul>
                        <li>外资公司注册、前海公司注册不适用本优惠政策；</li>
                        <li>如需办理批文的，批文部分另收费；</li>
                        <li>工本费,即办理注册必须成本，刻章等费用，若您自己办理，大概需800-1000元。</li>
                    </ul>
                </dd>
            </dl>
        </div>
    </div>

    <div class="mycase1">
        <a href="neizi_zc/200.html"><img src="{$template_dir}images/ad1.gif" alt="圆梦一号增值服务"></a>
    </div>

    <div class="tese2">
        <div class="catet">
            <dl>
                <dt><span>超值增值服务</span>尊享不停</dt>
                <dd class="tinfo">我们给您的服务，不仅仅是公司注册，还有如下增值服务：</dd>
                <dd>
                    <ul>
                        <li><span>（免费）</span>公司开业辅导        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          &nbsp; <span>&nbsp;（免费）</span>银行开户</li>
                        <li><span>（免费）</span>企业老总专项财税培训<span>&nbsp;（免费）</span>社保办理咨询</li>
                        <li><span>（免费）</span>一般纳税人认定申请<span>&nbsp;&nbsp;&nbsp;&nbsp;（免费）</span>人力资源咨询（招聘）</li>
                        <li><span>（免费）</span>商标注册/专利申请<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;（免费）</span>法律咨询</li>
                        <li><span>（免费）</span>财税疑难问题咨询&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;（收费）专业、规范代理记账报税服务</li>
                    </ul>
                </dd>
            </dl>
        </div>
        <div class="cateb">
            <dl>
                <dt>事业起步阶段<span>事太多?</span>助您做个<span>“甩手掌柜”</span></dt>
                <dd class="tinfo">圆梦壹号，专为创业而生！不仅为您<span>1元</span>注册深圳公司，还会根据您企业发展制定财税规划；为您办理银行开户；教您办理社保；教您签订劳动合同；若您没时间，还可协助您招聘企业员工；收发快递……真正360°全方位为您服务。<span>而这些，都是免费的</span>。</dd>
            </dl>
        </div>
    </div>

    <div class="mycase1">
        <a href="neizi_zc/200.html"><img src="{$template_dir}images/ad2.gif" alt="记账报税好处"></a>
    </div>

    <div class="benefit">
        <div class="title">代理记账6大好处</div>
        <div class="left">
            <dl class="fit1">
                <dt>01.超低成本</dt>
                <dd class="bf1">Low costs</dd>
                <dd class="bf2">仅为聘请专职会计成本的9%左右</dd>
            </dl>
            <dl class="fit3">
                <dt>03.及时报税</dt>
                <dd class="bf1">Timely tax returns</dd>
                <dd class="bf2">勿担心误报、漏报、迟报，若有失误造成罚款将由我司承担</dd>
            </dl>
            <dl class="fit5">
                <dt>05.财税指导</dt>
                <dd class="bf1">Taxation guidance</dd>
                <dd class="bf2">免去您疲于应付工商、税务等部门，尽力规避财务税务风险</dd>
            </dl>
        </div>
        <div class="right">
            <dl class="fit2">
                <dt>02.质量保证</dt>
                <dd class="bf1">Quality</dd>
                <dd class="bf2">资深会计师领衔，专业会计团队做账，严把质量关</dd>
            </dl>
            <dl class="fit4">
                <dt>04.稳定性好 </dt>
                <dd class="bf1">Good stability</dd>
                <dd class="bf2">企业会计工作不因企业财务人员变动而中断；</dd>
            </dl>
            <dl class="fit6">
                <dt>06.安全保密</dt>
                <dd class="bf1">Security</dd>
                <dd class="bf2">我们肩负为企业保密责任，绝不对外泄露企业机密</dd>
            </dl>
        </div>

        <div class="clear"></div>

        <div class="bftext">
            <dl>
                <dt>做账质量关乎企业稳健发展</dt>
                <dd>账务质量不过关，易造成多交税，增加成本；或造成少交税，会引起税局查账；且会阻碍企业发展，对企业信贷、融资、并购、上市等都会有影响。</dd>
            </dl>
        </div>
    </div>

    <div class="mycase1">
        <a href="jizhang/199.html"><img src="{$template_dir}images/ad3.gif" alt="了解更多圆梦一号记账报税服务"></a>
    </div>

</div>

<div class="main_q">
    <div class="main_m">
        <div class="power">
            <div class="title">公司实力</div>
        </div>
    </div>
</div>

<div class="main_m">
    <div class="casecustomer">
        <div class="case">
            <div class="title"><span>我们服务过</span> | Customer case<em>更多</em></div>
            <dl>
                <dd><img src="{$template_dir}images/case1.gif"></dd>
                <dd><img src="{$template_dir}images/case2.gif"></dd>
                <dd><img src="{$template_dir}images/case3.gif"></dd>
                <dd><img src="{$template_dir}images/case4.gif"></dd>
                <dd><img src="{$template_dir}images/case5.gif"></dd>
                <dd><img src="{$template_dir}images/case6.gif"></dd>
                <dd><img src="{$template_dir}images/case7.gif"></dd>
                <dd><img src="{$template_dir}images/case8.gif"></dd>
                <dd><img src="{$template_dir}images/case9.gif"></dd>
            </dl>
        </div>
        <div class="customer">
            <div class="title"><span>客户见证</span> | Customer testimonials<em>更多</em></div>
            <div class="content">
                <dl>
                    <dt><img src="{$template_dir}images/jz01.gif"></dt>
                    <dd class="ctit">福田马小姐：竟然1元为我注册深圳公司！</dd>
                    <dd class="cinfo">一开始我也有些难以置信，但仔细询问客服后得知，优惠竟然是真的，并非噱头，全套代办仅象征性收取1元服务费，连600注册工本费都帮我垫付了......</dd>
                    <dd class="cmore">查看详情</dd>
                </dl>
                <dl>
                    <dt><img src="{$template_dir}images/jz02.gif"></dt>
                    <dd class="ctit">龙华魏总：感谢圆梦壹号解了我“燃眉之急”</dd>
                    <dd class="cinfo">因生意需要急需注册一家新公司，但太忙没时间办理,多亏圆梦一号专业快速全程代办，还为我免费开银行账户，更让我惊喜的是竟然只收1元服务费.....</dd>
                    <dd class="cmore">查看详情</dd>
                </dl>
            </div>
        </div>
    </div>

    <div class="news">
        <div class="szwz">
            <script type="text/javascript">
                function nTabs0(thisObj,Num){
                    if(thisObj.className == "active0")return;
                    var tabObj = thisObj.parentNode.id;
                    var tabList = document.getElementById(tabObj).getElementsByTagName("li");
                    for(i=0; i < tabList.length; i++)
                    {
                        if (i == Num)
                        {
                            thisObj.className = "active0";
                            document.getElementById(tabObj+"_Content"+i).style.display = "block";
                        }else{
                            tabList[i].className = "normal0";
                            document.getElementById(tabObj+"_Content"+i).style.display = "none";
                        }
                    }
                }
            </script>

            <div class="cate_t">
                <ul id="myTab0">
                    <li class="active0" onclick="nTabs0(this,0);">深圳公司注册</li>
                    <li class="normal0" onclick="nTabs0(this,1);">外资公司注册</li>
                    <ul>
                    </ul></ul></div>
            <div class="content" id="myTab0_Content0" style="display: block; ">
                <dl>
                    <dd><a href="neizi_zc/200.html" title="深圳公司注册服务">深圳公司注册服务</a></dd>
                    <dd><a href="neizi_zc/198.html" title="2014年深圳公司注册新政策小结">2014年深圳公司注册新政策小结</a></dd>
                    <dd><a href="neizi_zc/14.html" title="企业冠省名称预先核准登记">企业冠省名称预先核准登记</a></dd>
                    <dd><a href="neizi_zc/13.html" title="深圳集团公司设立登记">深圳集团公司设立登记</a></dd>
                    <dd><a href="neizi_zc/12.html" title="深圳股份有限公司设立">深圳股份有限公司设立</a></dd>
                    <dd><a href="neizi_zc/11.html" title="深圳合伙企业设立登记">深圳合伙企业设立登记</a></dd>
                    <dd><a href="neizi_zc/10.html" title="常见企业经营范围规范用语">常见企业经营范围规范用语</a></dd>
                    <dd><a href="neizi_zc/9.html" title="深圳市有限公司注册登记">深圳市有限公司注册登记</a></dd>

                </dl>
            </div>
            <div class="content" id="myTab0_Content1" style="display: none; ">
                <dl>
                    <dd><a href="waizi_zc/119.html" title="外商独资企业设立登记">外商独资企业设立登记</a></dd>
                    <dd><a href="waizi_zc/118.html" title="外商投资企业分支机构设立登记">外商投资企业分支机构设立登记</a></dd>
                    <dd><a href="waizi_zc/117.html" title="中外合资企业设立登记">中外合资企业设立登记</a></dd>
                    <dd><a href="waizi_zc/116.html" title="深圳外资公司注册">深圳外资公司注册</a></dd>
                    <dd><a href="waizi_zc/115.html" title="外资公司注册条件">外资公司注册条件</a></dd>
                    <dd><a href="waizi_zc/114.html" title="深圳代表处注册">深圳代表处注册</a></dd>
                    <dd><a href="waizi_zc/113.html" title="出口许可证办理条件及流程">出口许可证办理条件及流程</a></dd>
                    <dd><a href="waizi_zc/112.html" title="进出口权办理流程">进出口权办理流程</a></dd>

                </dl>
            </div>
        </div>

        <div class="qhcj">
            <script type="text/javascript">
                function nTabs(thisObj,Num){
                    if(thisObj.className == "active1")return;
                    var tabObj = thisObj.parentNode.id;
                    var tabList = document.getElementById(tabObj).getElementsByTagName("li");
                    for(i=0; i < tabList.length; i++)
                    {
                        if (i == Num)
                        {
                            thisObj.className = "active1";
                            document.getElementById(tabObj+"_Content"+i).style.display = "block";
                        }else{
                            tabList[i].className = "normal1";
                            document.getElementById(tabObj+"_Content"+i).style.display = "none";
                        }
                    }
                }
            </script>

            <div class="cate_t">
                <ul id="myTab1">
                    <li class="active1" onclick="nTabs(this,0);">前海公司注册</li>
                    <li class="normal1" onclick="nTabs(this,1);">常见问题</li>
                    <ul>
                    </ul></ul></div>
            <div class="content" id="myTab1_Content0" style="display: block; ">
                <dl>
                    <dd><a href="qianhai/197.html" title="前海企业所得税优惠政策和目录出台">前海企业所得税优惠政策和目录出台</a></dd>
                    <dd><a href="qianhai/196.html" title="深圳前海企业设立的基本要求">深圳前海企业设立的基本要求</a></dd>
                    <dd><a href="qianhai/195.html" title="深圳前海企业注册的申请设立流程">深圳前海企业注册的申请设立流程</a></dd>
                    <dd><a href="qianhai/194.html" title="深圳前海供应链管理公司注册">深圳前海供应链管理公司注册</a></dd>
                    <dd><a href="qianhai/193.html" title="深圳前海互联网金融服务公司注册">深圳前海互联网金融服务公司注册</a></dd>
                    <dd><a href="qianhai/192.html" title="深圳前海金融服务公司注册">深圳前海金融服务公司注册</a></dd>
                    <dd><a href="qianhai/191.html" title="深圳前海小额贷款公司注册">深圳前海小额贷款公司注册</a></dd>
                    <dd><a href="qianhai/190.html" title="深圳前海融资租赁公司注册">深圳前海融资租赁公司注册</a></dd>

                </dl>
            </div>
            <div class="content" id="myTab1_Content1" style="display: none; ">
                <dl>
                    <dd><a href="wenti_zc/101.html" title="公司必须先办理名称预先核准？">公司必须先办理名称预先核准？</a></dd>
                    <dd><a href="wenti_zc/100.html" title="公司名称加“广东省”需要哪里审批？">公司名称加“广东省”需要哪里审批？</a></dd>
                    <dd><a href="wenti_zc/99.html" title="公司名称能使“集团”字样吗？">公司名称能使“集团”字样吗？</a></dd>
                    <dd><a href="wenti_zc/98.html" title="公司名称前面可以不加“深圳市”吗？">公司名称前面可以不加“深圳市”吗？</a></dd>
                    <dd><a href="wenti_zc/97.html" title="公司名称中能不能不要“有限”这两个字？">公司名称中能不能不要“有限”这两个字？</a></dd>
                    <dd><a href="wenti_zc/96.html" title="可以用国外某地地名作为公司名称吗？">可以用国外某地地名作为公司名称吗？</a></dd>
                    <dd><a href="wenti_zc/95.html" title="可以注册“研究所”公司吗？">可以注册“研究所”公司吗？</a></dd>
                    <dd><a href="wenti_zc/94.html" title="企业名称能使用阿拉伯数字吗？">企业名称能使用阿拉伯数字吗？</a></dd>

                </dl>
            </div>


        </div>
        <div class="gszc">
            <dl>
                <dt>我要注册？</dt>
                <dd><a href="leixing/175.html" target="_blank">运输公司注册</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="leixing/173.html" target="_blank">货运代理公司注册</a></dd>
                <dd><a href="leixing/174.html" target="_blank">物流公司注册</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="leixing/170.html" target="_blank">园林绿化公司注册</a></dd>
                <dd><a href="leixing/172.html" target="_blank">贸易公司注册</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="leixing/168.html" target="_blank">酒店管理公司注册</a></dd>
                <dd><a href="leixing/171.html" target="_blank">服装公司注册</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="leixing/166.html" target="_blank">技术研发公司注册</a></dd>
                <dd><a href="leixing/167.html" target="_blank">科技公司注册</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="leixing/158.html" target="_blank">餐饮管理公司注册</a></dd>
                <dd><a href="leixing/165.html" target="_blank">电子公司注册</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="leixing/157.html" target="_blank">医疗器械公司注册</a></dd>
                <dd><a href="leixing/162.html" target="_blank">实业公司注册</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="leixing/155.html" target="_blank">文化传播公司注册</a></dd>
                <dd><a href="leixing/161.html" target="_blank">股份公司注册</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="leixing/149.html" target="_blank">展览展示公司注册</a></dd>
                <dd><a href="leixing/169.html" target="_blank">物业公司注册</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="leixing/164.html" target="_blank">进出口公司注册</a></dd>
                <dd><a href="leixing/163.html" target="_blank">商务公司注册</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="leixing/156.html" target="_blank">保健品公司注册</a></dd>
                <dd><a href="leixing/160.html" target="_blank">集团公司注册</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="leixing/148.html" target="_blank">装饰公司注册</a></dd>
                <dd><a href="leixing/159.html" target="_blank">食品公司注册</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="leixing/150.html" target="_blank">设计公司注册</a></dd>
            </dl>
        </div>
    </div>
</div>

<div class="clear"></div>
{include file="footer.phtml"}
</body>
</html>
