<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<div class="cates">
    <div class="cate_t">{$page_title}</div>
    <div class="content">
        <dl>
            {foreach from=$top_article item=article}
            <dd><a href="article.php?id={$article.id}">{$article.title|truncate:12}</a></dd>
            {/foreach}
        </dl>
    </div>
</div>
<div class="tel">
    <dl>
        <dt><img src="{$template_dir}images/ad4.gif" alt=""></dt>
        <dd>{$config.owner}</dd>
        <dd>创业热线<font color="#FF0000"><b>：{$config.phone}</b></font></dd>
        <dd>在线咨询：
            <a href="http://wpa.qq.com/msgrd?v=3&uin={$config.server}site={$config.domain}&menu=yes">
                <img src="http://wpa.qq.com/pa?p=2:{$config.server}:51" border="0" alt="QQ">
            </a>
        <dd>公司地址：{$config.address}</dd>
    </dl>
</div>
