{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        <div class="clear"></div>
    </div>
    <div class="sysconf-main">
        <form id="friend-form" name="friend-form" method="post" onsubmit="return do_submit();">
            <fieldset>
                <p class="clear">
                    <label class="l-title">链接名称:</label>
                    <input class="text-input w300" type="text" id="name" name="name" placeholder="请输入链接名称"/>
                    <span class="error-input" id="name-error">{if isset($error.name)}{$error.name}{/if}</span>
                </p>
                <p class="clear">
                    <label class="l-title">url:</label>
                    <input class="text-input w300" type="text" id="url" name="url" placeholder="请输入url"/>
                    <span class="error-input" id="url-error">{if isset($error.url)}{$error.url}{/if}</span>
                </p>
                <p class="clear">
                    <label class="l-title">链接排序:</label>
                    <input class="text-input w300" type="number" id="order_view" name="order_view" placeholder="请输入排序" value="50"/>
                    <span class="error-input" id="order_view-error">{if isset($error.order_view)}{$error.order_view}{/if}</span>
                </p>
                <p class="clear">
                    <label class="l-title">权重传递:</label>
                    <input type="radio" name="no_followed" value="1" checked="checked"/><em>否</em>&nbsp;
                    <input type="radio" name="no_followed" value="0"/><em>是</em>
                    <span class="error-input" id="no_followed-error">{if isset($error.no_followed)}{$error.no_followed}{/if}</span>
                </p>
                <p class="clear">
                    <label class="l-title">链接类型:</label>
                    <select name="type" id="type" class="w150" onchange="select_link_type(this.value);">
                        <option value="text">文字链接</option>
                        <option value="img">图片链接</option>
                    </select>
                    <span class="error-input" id="type-error">{if isset($error.type)}{$error.type}{/if}</span>
                </p>
                <p class="clear" style="display: none" id="img-input">
                    <label class="l-title">链接图片：</label>
                    <input type="button" class="text-input" id="select-image" value="请选择链接图片" style="cursor:pointer">
                    <input type="hidden" class="" name="img" id="img" value=""/>
                    <span class="error-input" id="img-error">{if isset($error.img)}{$error.img}{/if}</span>
                </p>
                <p id="img-show" style="display: none">
                    <label class="l-title"></label>
                    <img id="show-image" alt="" src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image">
                </p>
                <p>
                    <label class="l-title"></label>
                    <a class="btn btn-primary" id="submit-btn" href="javascript:;">
                        新增<img src="images/btn_loading.gif" class="btn-loading-img"/>
                    </a>&nbsp;
                    <input type="hidden" name="opera" value="add"/>
                    <a href="javascript:history.go(-1);" class="btn btn-primary">返回</a>
                </p>                
            </fieldset>
        </form> 
    </div>
</div>
<div id="mask"></div>
<script type="text/javascript">
$(function() {
    $("#submit-btn").click(do_submit);
});
/**
* 这个解决方案可以作为Ajax提交表单的模板
* 1、form的提交操作托管给do_submit处理;
* 2、Ajax操作分为两部分，第一部分do_submit作为提交前的参数验证，第二部分do_resposne作为返回代码的处理;
* 3、仅支持post方式提交表单;
* 4、需要在提交按钮加入提交中的加载图片，以及遮罩层代码<div id="mask"></div>
**/
function do_submit() {
    //参数校验
    var url = $("#url").val().trim();
    var img = $("#img").val().trim();
    var no_followed = $("input[name=no_followed]")[0].checked ? $("input[name=no_followed")[0].value : $("input[name=no_followed")[1].value;
    no_followed = parseInt(no_followed);
    var type = $("#type").val().trim();
    var name = $("#name").val().trim();
    var order_view = parseInt($("#order_view").val().trim());
    var flag = true;

    if(url == "") {
        $("#url-error").text("-请输入url");
        flag = false;
    } else {
        $("#url-error").text("");
    }

    if(type == "img" && img == "") {
        $("#img-error").text("-请上传链接图片");
        flag = false;
    } else {
        $("#img-error").text("");
    }

    if(type != "text" && type != "img")
    {
        $("#type-error").text("-请选择链接类型");
        flag = false;
    } else {
        $("#type-error").text("");
    }

    if(name == "") {
        $("#name-error").text("-请输入链接名称");
        flag = false;
    } else {
        $("#name-error").text("");
    }

    if(isNaN(no_followed)) {
        no_followed = 1;
    }

    if(isNaN(order_view) || order_view <= 0)
    {
        $("#order_view-error").text("-请输入大于0的整数");
        flag = false;
    } else {
        $("#order_view-error").text("");
    }

    if(flag) {
        flag = true;
        //启用过渡效果
        $(".btn-loading-img").show();
        $("#submit-btn").addClass("btn-disabled");
        $("#mask").show();

        var params = { "opera":"add", "url":url, "name":name, "img":img, "order_view":order_view, "type":type, "no_followed":no_followed };
        var url = "friend.php";
        $.post(url, params, do_response, "json");
    }

    return flag;
}

function do_response(result) {
    //关闭过渡效果
    $(".btn-loading-img").hide();
    $("#submit-btn").removeClass("btn-disabled");
    $("#mask").hide();
    //处理返回结果
    if(result.error == 0) {
        alert(result.msg);
        document.forms['friend-form'].reset();
        $("#show-img").attr("src", "http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image");
        $("#img-input").hide();
        $("#img-show").hide();
    } else {
        if(result.msg != "") {
            alert(result.msg);
        }

        if(result.errmsg.length) {
            for(var id in result.errmsg) {
                $("#"+id+"-error").text(result.errmsg[id]);
            }
        }
    }
}
/*----------------  Ajax end ---------------------*/

function select_link_type(type)
{
    if(type == "img")
    {
        $("#img-input").show();
        $("#img-show").show();
    } else {
        $("#img-input").hide();
        $("#img-show").hide();
    }
}
</script>
<link rel="stylesheet" type="text/css" href="../plugins/kindeditor/plugins/code/prettify.css"/>
<link rel="stylesheet" type="text/css" href="../plugins/kindeditor/themes/default/default.css"/>
<script type="text/javascript" src="../plugins/kindeditor/kindeditor-all-min.js"></script>
<script type="text/javascript">
    KindEditor.ready(function(K) {
        var editor = K.editor({
            allowFileManager : true,
            uploadJson : 'plugin_upload_json.php',
            fileManagerJson : '../plugins/kindeditor/file_manager_json.php'
        });
        K('#select-image').click(function() {
            editor.loadPlugin('fileupload', function() {
                editor.plugin.imageDialog({
                    imageUrl : '',
                    clickFn : function(url, title, width, height, border, align) {
                        if( !width ) {
                            width = '200';
                            width = (width == '') ? '75px' : width + 'px'
                        }
                        if( !height ) {
                            height = '100';
                            height = (height == '') ? '75px' : height + 'px'
                        }

                        K('#img').val(url);
                        K('#show-image').attr('src', url);
                        K('#show-image').css('width', width);
                        K('#show-image').css('height', height);                        
                        K('#show-image').css('display', 'block');
                        editor.hideDialog();
                    }
                });
            });
        });
    });
</script>
<!-- END content -->

{include file="library/footer.lbi"}
</body>
</html>
