{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<script type="text/javascript" src="js/ajaxfileupload.js"></script>
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        <div class="clear"></div>
    </div>
    <div class="sysconf-main">
        <form id="friend-form" name="friend-form" method="post" onsubmit="return do_submit();">
            <fieldset>
                <p class="clear">
                    <label class="l-title">链接名称:</label>
                    <input class="text-input w300" type="text" value="{$link.name}" id="name" name="name" placeholder="请输入链接名称"/>
                    <span class="error-input" id="name-error">{if isset($error.name)}{$error.name}{/if}</span>
                </p>
                <p class="clear">
                    <label class="l-title">url:</label>
                    <input class="text-input w300" type="text" value="{$link.url}" id="url" name="url" placeholder="请输入url"/>
                    <span class="error-input" id="url-error">{if isset($error.url)}{$error.url}{/if}</span>
                </p>
                <p class="clear">
                    <label class="l-title">链接排序:</label>
                    <input class="text-input w300" type="number" value="{$link.order_view}" id="order_view" name="order_view" placeholder="请输入排序" value="50"/>
                    <span class="error-input" id="order_view-error">{if isset($error.order_view)}{$error.order_view}{/if}</span>
                </p>
                <p class="clear">
                    <label class="l-title">权重传递:</label>
                    <input type="radio" name="no_followed" value="1" {if $link.no_followed eq 1}checked="checked"{/if}/><em>否</em>&nbsp;
                    <input type="radio" name="no_followed" value="0" {if $link.no_followed eq 0}checked="checked"{/if}/><em>是</em>
                    <span class="error-input" id="no_followed-error">{if isset($error.no_followed)}{$error.no_followed}{/if}</span>
                </p>
                <p class="clear">
                    <label class="l-title">链接类型:</label>
                    <select name="type" id="type" class="w150" onchange="select_link_type(this.value);">
                        <option value="text" {if $link.type eq "text"}selected="selected"{/if}>文字链接</option>
                        <option value="img" {if $link.type eq "img"}selected="selected"{/if}>图片链接</option>
                    </select>
                    <span class="error-input" id="type-error">{if isset($error.type)}{$error.type}{/if}</span>
                </p>
                <p class="clear" {if $link.type eq "text"}style="display: none"{/if} id="img-input">
                    <label class="l-title">链接图片:</label>
                    <input type="hidden" name="img" value="{$link.img}" id="img"/>
                    <input type="file" name="upload" id="upload"/>
                    <input type="button" class="btn" name="upload_btn" id="upload_btn" value="上传"/>
                    <img src="../{$link.img}" id="upload-img"/>
                    <span class="error-input" id="img-error">{if isset($error.img)}{$error.img}{/if}</span>
                </p>
                <p>
                    <label class="l-title"></label>
                    <a class="btn btn-primary" id="submit-btn" href="javascript:;">
                        修改<img src="images/btn_loading.gif" class="btn-loading-img"/>
                    </a>&nbsp;
                    <input type="hidden" name="opera" value="edit"/>
                    <input type="hidden" name="eid" id="eid" value="{$link.id}"/>
                    <a href="javascript:history.go(-1);" class="btn btn-primary">返回</a>
                </p>                
            </fieldset>
        </form> 
    </div>
</div>
<div id="mask"></div>
<script type="text/javascript">
$(function() {
    $("#submit-btn").click(do_submit);
});
/**
* 这个解决方案可以作为Ajax提交表单的模板
* 1、form的提交操作托管给do_submit处理;
* 2、Ajax操作分为两部分，第一部分do_submit作为提交前的参数验证，第二部分do_resposne作为返回代码的处理;
* 3、仅支持post方式提交表单;
* 4、需要在提交按钮加入提交中的加载图片，以及遮罩层代码<div id="mask"></div>
**/
function do_submit() {
    //参数校验
    var url = $("#url").val().trim();
    var img = $("#img").val().trim();
    var no_followed = $("input[name=no_followed]")[0].checked ? $("input[name=no_followed")[0].value : $("input[name=no_followed")[1].value;
    no_followed = parseInt(no_followed);
    var type = $("#type").val().trim();
    var name = $("#name").val().trim();
    var order_view = parseInt($("#order_view").val().trim());
    var eid = parseInt($("#eid").val().trim());
    var flag = true;

    if(isNaN(eid) || eid <= 0)
    {
        alert("参数错误");
        flag = false;
    }

    if(url == "") {
        $("#url-error").text("-请输入url");
        flag = false;
    } else {
        $("#url-error").text("");
    }

    if(type == "img" && img == "") {
        $("#img-error").text("-请上传链接图片");
        flag = false;
    } else {
        $("#img-error").text("");
    }

    if(type != "text" && type != "img")
    {
        $("#type-error").text("-请选择链接类型");
        flag = false;
    } else {
        $("#type-error").text("");
    }

    if(name == "") {
        $("#name-error").text("-请输入链接名称");
        flag = false;
    } else {
        $("#name-error").text("");
    }

    if(isNaN(no_followed)) {
        no_followed = 1;
    }

    if(isNaN(order_view) || order_view <= 0)
    {
        $("#order_view-error").text("-请输入大于0的整数");
        flag = false;
    } else {
        $("#order_view-error").text("");
    }

    if(flag) {
        flag = true;
        //启用过渡效果
        $("#submit-btn").addClass("btn-disabled");
        $(".btn-loading-img").show();
        $("#mask").show();

        var params = { "opera":"edit", "url":url, "name":name, "img":img, "order_view":order_view, "type":type, "no_followed":no_followed, "eid":eid };
        var url = "friend.php";
        $.post(url, params, do_response, "json");
    }

    return flag;
}

function do_response(result) {
    //关闭过渡效果
    $(".btn-loading-img").hide();
    $("#submit-btn").removeClass("btn-disabled");
    $("#mask").hide();
    //处理返回结果
    if(result.error == 0) {
        alert(result.msg);
        $("#upload-img").attr("src", "about:blank");
        window.location.reload();
    } else {
        if(result.msg != "") {
            alert(result.msg);
        }

        if(result.errmsg.length) {
            for(var id in result.errmsg) {
                $("#"+id+"-error").text(result.errmsg[id]);
            }
        }
    }
}
/*----------------  Ajax end ---------------------*/

function select_link_type(type)
{
    if(type == "img")
    {
        $("#img-input").show();
    } else {
        $("#img-input").hide();
    }
}

function ajaxFileUpload()
{
	$("#loading").ajaxStart(function(){
		$(this).show();
	}).ajaxComplete(function(){
		$(this).hide();
	});

	$.ajaxFileUpload({
		url:'doajaxfileupload.php',
		secureuri:false,
		fileElementId:'upload',
		dataType: 'json',
		data:{ name:'logan', id:'id' },
		success: function (data, status) {
			if(typeof(data.error) != 'undefined') {
				if(data.error != '') {
					alert(data.error);
				} else {
                    alert(data.msg);
                    $("#upload-img").attr("src", "../"+data.file);
                    $("#img").val(data.file);
				}
			}
		},

		error: function (data, status, e) {
			alert(e);
		}
	});
		
	return false;
}

$(function() {
    $("#upload_btn").click(ajaxFileUpload);
});
</script>
<!-- END content -->

{include file="library/footer.lbi"}
</body>
</html>
